backend:
    name: github
    repo: jlooper/quicknoms-vuepress
    branch: master # Branch to update (optional; defaults to master)
media_folder: 'docs/.vuepress/public/images'
public_folder: 'docs/.vuepress/dist/'
collections:
    - name: 'recipes' # Used in routes, e.g., /admin/collections/blog
      label: 'Recipe' # Used in the UI
      folder: 'docs/yum/recipes' # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Type', name: 'type', default: 'recipe', widget: 'string' }
          - { label: 'Category', name: 'category', widget: 'string' }
          - { label: 'ImagePath', name: 'imagepath', widget: 'string' }
          - { label: 'Layout', name: 'layout', default: 'RecipeLayout', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Ingredients', name: 'ingredients', widget: 'list' }
          - { label: 'Tools', required: false, name: 'tools', widget: 'list' }
          - { label: 'Method', required: false, name: 'method', widget: 'markdown' }
    - name: 'videos' # Used in routes, e.g., /admin/collections/blog
      label: 'Videos' # Used in the UI
      folder: 'docs/videos' # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Type', name: 'type', default: 'video', widget: 'string' }
          - { label: 'EmbedUrl', name: 'embedurl', widget: 'string' }
          - { label: 'Layout', name: 'layout', default: 'VideoLayout', widget: 'string' }
